# Generated by Django 3.2.9 on 2021-11-11 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0003_restaurant_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favorites',
            field=models.ManyToManyField(through='favamealapi.FavoriteMeal', to=settings.AUTH_USER_MODEL),
        ),
    ]
