# Generated by Django 3.2.9 on 2021-11-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favamealapi', '0005_meal_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ratings',
        ),
    ]
